#!/usr/bin/env python3
"""Generate the site home page (index.html) from the members app (app/index.html).

The home page IS the markets view: same app, same assets (served from app/assets/), with paths and
the public-data/site-root config adjusted for the site root. Re-run after changing app/index.html.
"""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent
s = (root / "app" / "index.html").read_text()
s = s.replace('href="assets/', 'href="app/assets/').replace('src="assets/', 'src="app/assets/')
s = s.replace('<meta name="robots" content="noindex,nofollow">',
              '<meta name="description" content="Closer AI: browse live prediction markets by category with price charts, then ask your own AI to analyze them. Read-only, never places bets.">')
s = re.sub(r"<title>.*?</title>", "<title>Closer AI · Prediction markets</title>", s, count=1)
s = re.sub(r'(<script src="app/assets/config\.js[^"]*"></script>)',
           r'\1<script>CLOSER_CONFIG.publicData = "data/"; CLOSER_CONFIG.siteRoot = "";</script>', s, count=1)
assert 'CLOSER_CONFIG.siteRoot = ""' in s and 'src="assets/' not in s and 'href="assets/' not in s
s = "<!-- GENERATED by build_home.py from app/index.html. Edit the app, then re-run. -->\n" + s
(root / "index.html").write_text(s)
print("index.html regenerated")
